thisdir := vbnc/cecil
SUBDIRS := Mono.Cecil Mono.Cecil.Mdb

include ../../build/rules.make

clean-local test-local run-test-local run-test-ondotnet-local all-local install-local uninstall-local:
	@:

dist-local: dist-default
