thisdir = vbruntime
include ../build/rules.make

SUBDIRS := Microsoft.VisualBasic

DISTFILES = Makefile

clean-local test-local run-test-local run-test-ondotnet-local all-local install-local uninstall-local:
        @:

dist-local: dist-default
