thisdir = vbruntime
include ../build/rules.make

SUBDIRS := Microsoft.VisualBasic

clean-local dist-local test-local run-test-local run-test-ondotnet-local all-local install-local uninstall-local:
        @:
