thisdir = tools
include ../build/rules.make

SUBDIRS := extract-source

DISTFILES = Makefile

clean-local dist-local test-local run-test-local run-test-ondotnet-local all-local install-local uninstall-local:
        @:
